spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
#     ??????? always, embedded? ???? ???, ????? never? ??
#      SQL? DDL? batch? ?? ????? ????? ??????.
      initialize-schema: always
#?? job?????? ?? ?? ?? + application configuration? Program arguments?? ??
